name: MATLAB Tests

# Controls when the action will run. 
on: [push]

jobs:

  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Run all tests
        uses: matlab-actions/run-tests@v1
